export const DATA_ANIMATIONS: string[] = ['slit', 'slithor', 'bounce', 'roll'];

export const DATA_EFFECTS: string[] = [
  'none',
  'fade',
  'scale',
  'zoomfade',
  'slideinright',
  'slideinleft',
  'slideintop',
  'slideinbottom',
  'newspaper',
  'fallcenter',
  'fallleft',
  'fallright',
  'fliphorleft',
  'fliphorright',
  'flipvertop',
  'flipverbottom',
  'flipsign',
  'flipsignfront',
  'slit',
  'slithor',
  'bounce',
  'roll',
  'rotatebottom',
  'rotatetop',
  'rotateleft',
  'rotateright',
];
